blank_issues_enabled: true
contact_links:
  - name: TruckTracker Discussions
    url: https://github.com/Nixxzzzzz/truck_tracker/discussions
    about: Please ask questions and discuss ideas with the team.
